site_name: YORM
site_description: Automatic object YAML mapping for Python.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/yorm
# google_analytics: ['XX-XXXXXXXX-XX', 'jacebrowning.github.io/template-python-demo']

theme: mkdocs

pages:
- Home: index.md
- About:
  - 'Release Notes': about/changes.md
  - Contributing: about/contributing.md
  - License: about/license.md
