site_name: YORM
site_description: Automatic object-YAML mapping for Python.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/yorm

theme: readthedocs

pages:
- Home: index.md
- API:
  - Instance Mapping: api/instance-mapping.md
  - Class Mapping: api/class-mapping.md
  - Builtin Types: api/builtin-types.md
  - Custom Types: api/custom-types.md
  - Utilities: api/utilities.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
